version: '3.8'

services:
  web:
    build: .
    container_name: laravel-web
    ports:
      - "8080:80"  # Laravel diakses via http://localhost:8080
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medcare
      MYSQL_USER: root
      MYSQL_PASSWORD: ""  # Sama seperti di .env
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
